### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by stylebased** [HaoliangZhou/CEPrompt#1]
Hi,
I am really impressed by the performance of your model. However, I can not duplicate your results because of missing functions. e.g. forward_maple in CLIPVIT, MultiModalPromptLearner. Can you add these functions to github? 
Best

**Comment by HaoliangZhou** [comment]
Thank you for your attention. 
This is caused by some function name changes. Are you loading the pre-trained model I provided, if so, it seems that you need to change `forward_cat` to `forward_maple` in CLIPVIT, and `CATPromptLearner` to `MultiModalPromptLearner` in cat.py. if you are training from scratch, then you should not encounter the above problem. Feel free to discuss with us if you have any problems.
